### ISSUE TITLE
Error Messages when adding snippets to Sublime 3

### ISSUE THREAD

**Issue by pixeljugglerdan** [garyriverson/perchsnippets#1]
I get three Error Messages when adding snippets to Sublime 3

"No content for snippet Packages/User/perchsnippets-master/podcasts/templates/podcasts-template.sublime-snippet"

"Error parsing snippet xml: expected = in file Packages/User/perchsnippets-master/podcasts/templates/podcasts-rss-template.sublime-snippet on line: 7"

"Error parsing snippet xml: expected = in file Packages/User/perchsnippets-master/podcasts/templates/podcasts-rss-channel.sublime-snippet on line: 13"

**Comment by garyriverson** [comment]
Okay, I'll check that out.

**Comment by garyriverson** [comment]
The latest commit removes those three files. The first was empty, and there doesn't seem to be anything to actually put into the snippet. The other two contained nested CDATA, which isn't allowed within a snippet. So you should be good to go now.
